### ISSUE TITLE
Bug: Incorrect report of a dead assignment

### ISSUE THREAD

**Issue by stuartherbert** [scrutinizer-ci/php-analyzer#553]
The assignment is part of a unit test method which as an @expectedException annotation. It is this assignment that triggers the exception, and is necessary.

see https://scrutinizer-ci.com/g/datasift/storyplayer/inspections/d5abaa28-5115-4698-a7f4-41712b43981d/issues/files/src/tests/unit-tests/php/DataSift/Storyplayer/ConfigLib/ConfigListTest.php?status=existing&orderField=path&order=asc&issueId=8aa1793e-b3f1-420e-901c-c9c322125b0a

**Comment by schmittjoh** [comment]
Thanks for reporting; unfortunately, this issue looks correct. You should be able to trigger the exception without assigning the result to ``$obj``. 

Ignoring the issue is fine too of course as it does not cause any harm in this case. It is not something that we can/should fix in the analyzer though.
