### ISSUE TITLE
Return type not recognized properly

### ISSUE THREAD

**Issue by vpassapera** [scrutinizer-ci/php-analyzer#737]
The method was marked with return type array...never string :)

see https://scrutinizer-ci.com/g/vpassapera/TdnForgeBundle/issues/develop/files/Services/Symfony/Routing/Loader/Driver/YamlLoader.php?orderField=path&order=asc&issueId=e6f05242-c652-44a0-bc45-4b22fc80b5c0

And ofc, Thank you for this fantastic tool!

**Comment by nasimnabavi** [comment]
Thank you for the report. 
Actually the "parse($contents)" method is returning "Parser.parse(...)", which according to symfony's api has a mixed return type:
http://api.symfony.com/2.6/Symfony/Component/Yaml/Parser.html
Unfortunately we cannot fix this issue, since it might break other checks.

Thank you again
